"""CLI entry point: bootstrap, run, fetch, show, why, install-agent."""

from __future__ import annotations

import argparse
import getpass
import logging
import sys
from datetime import UTC, datetime
from pathlib import Path

from recto import config, dedupe, keychain, score
from recto.logging_setup import configure_logging
from recto.models import Paper
from recto.profile import build
from recto.sources import arxiv, openalex, scholar_alerts, semanticscholar
from recto.store import Store

logger = logging.getLogger(__name__)

DEFAULT_CONTACT_EMAIL = "sasikirangaddipati@gmail.com"
DEFAULT_ORCID_ID = "0000-0003-3098-4592"
DEFAULT_ARXIV_CATEGORIES = ["cs.AI", "cs.LG", "stat.ML", "cs.MA"]


def _profile_md_template(orcid_id: str) -> str:
    today = datetime.now().strftime("%Y-%m-%d")
    return f"""# Research Profile

_Generated by `recto bootstrap` on {today}. Edit freely — this file
overrides inferred interests from your publication history where they
conflict._

## Current focus

<!-- 2-4 sentences on what you're actively working on now, including things
     you haven't published on yet. This section carries the most weight. -->

## Background (inferred from ORCID: {orcid_id})

<!-- Populated from your ORCID publication history; edit or remove entries
     that no longer reflect your interests. -->

## Explicit keywords

<!-- One per line, optional. Boosts scoring directly regardless of the
     prose above. -->
"""


def fetch_all_sources(cfg: config.Config) -> dict[str, list[Paper]]:
    results: dict[str, list[Paper]] = {}
    contact_email = cfg.general.contact_email

    if cfg.sources.arxiv.enabled:
        try:
            results["arxiv"] = arxiv.fetch(
                categories=cfg.topics.arxiv_categories,
                lookback_days=cfg.sources.arxiv.lookback_days,
                max_results=cfg.sources.arxiv.max_results_per_query,
                contact_email=contact_email,
            )
        except Exception:
            logger.exception("arxiv fetch failed unexpectedly")
            results["arxiv"] = []

    if cfg.sources.openalex.enabled:
        openalex_papers: list[Paper] = []
        try:
            if cfg.topics.keywords:
                openalex_papers += openalex.fetch_keyword(
                    query=" OR ".join(cfg.topics.keywords),
                    max_results=cfg.sources.openalex.max_results,
                    contact_email=contact_email,
                    lookback_days=cfg.sources.openalex.lookback_days,
                )
            if cfg.sources.openalex.citation_graph_enabled:
                index = build.load_index(config.profile_index_path())
                if index is not None:
                    cap = cfg.sources.openalex.citation_graph_max_seed_works
                    openalex_papers += openalex.fetch_citing_user_works(
                        index.seed_work_ids[:cap],
                        cfg.sources.openalex.max_results,
                        contact_email,
                        lookback_days=cfg.sources.openalex.lookback_days,
                    )
                    openalex_papers += openalex.fetch_citing_shared_references(
                        index.reference_work_ids[:cap],
                        cfg.sources.openalex.max_results,
                        contact_email,
                        lookback_days=cfg.sources.openalex.lookback_days,
                    )
                else:
                    logger.info("no profile index yet, skipping openalex citation-graph channels")
        except Exception:
            logger.exception("openalex fetch failed unexpectedly")
        results["openalex"] = openalex_papers

    if cfg.sources.scholar_alerts.enabled:
        try:
            username = cfg.sources.scholar_alerts.imap_username
            password = keychain.get_secret(keychain.SERVICE_IMAP, username)
            if not password:
                logger.warning("scholar_alerts enabled but no IMAP password in Keychain, skipping")
                results["scholar_alerts"] = []
            else:
                results["scholar_alerts"] = scholar_alerts.fetch(
                    imap_host=cfg.sources.scholar_alerts.imap_host,
                    imap_port=cfg.sources.scholar_alerts.imap_port,
                    imap_username=username,
                    imap_password=password,
                    mail_folder=cfg.sources.scholar_alerts.mail_folder,
                    lookback_days=cfg.sources.scholar_alerts.lookback_days,
                    mark_as_read=cfg.sources.scholar_alerts.mark_as_read,
                )
        except Exception:
            logger.exception("scholar_alerts fetch failed unexpectedly")
            results["scholar_alerts"] = []

    return results


def cmd_bootstrap(
    home: Path, *, orcid_id: str, contact_email: str, arxiv_categories: list[str]
) -> int:
    cfg_path = config.config_path(home)
    if cfg_path.exists():
        print(f"{cfg_path} already exists, leaving it as-is.")
    else:
        email_address = input("Outlook email address (delivery target): ").strip()
        if not email_address:
            print("An email address is required to configure delivery.", file=sys.stderr)
            return 1
        config.write_default_config(
            home=home,
            contact_email=contact_email,
            orcid_id=orcid_id,
            email_address=email_address,
            arxiv_categories=arxiv_categories,
        )
        print(f"Wrote {cfg_path}")

    cfg = config.load_config(home)

    outlook_address = cfg.delivery.email_cfg.from_address
    if not keychain.get_secret(keychain.SERVICE_OUTLOOK, outlook_address):
        pw = getpass.getpass(f"Outlook password for {outlook_address} (stored in Keychain only): ")
        if pw:
            keychain.set_secret(keychain.SERVICE_OUTLOOK, outlook_address, pw)
            print("Stored Outlook password in Keychain.")

    if not keychain.get_secret(keychain.SERVICE_OPENROUTER, "api-key"):
        api_key = getpass.getpass("OpenRouter API key (stored in Keychain only): ")
        if api_key:
            keychain.set_secret(keychain.SERVICE_OPENROUTER, "api-key", api_key)
            print("Stored OpenRouter API key in Keychain.")

    profile_md_path = home / cfg.profile.profile_md_path
    if not profile_md_path.exists():
        profile_md_path.write_text(_profile_md_template(cfg.profile.orcid_id))
        print(f"Wrote {profile_md_path} — edit it to refine your interests.")

    print("Building profile index from ORCID + profile.md ...")
    prof_index = build.build_index(
        orcid_id=cfg.profile.orcid_id,
        profile_md_text=profile_md_path.read_text(),
        contact_email=cfg.general.contact_email,
        recency_half_life_days=cfg.profile.recency_half_life_days,
        profile_md_dominance=cfg.profile.profile_md_dominance,
    )
    build.save_index(prof_index, config.profile_index_path())
    top_terms = ", ".join(t for t, _ in prof_index.top_terms[:8])
    print(
        f"Profile index built: {len(prof_index.seed_work_ids)} of your papers resolved, "
        f"{len(prof_index.coauthor_names)} co-authors, "
        f"{len(prof_index.reference_work_ids)} reference works.\nTop terms: {top_terms}"
    )
    return 0


def cmd_fetch(home: Path) -> int:
    cfg = config.load_config(home)
    results = fetch_all_sources(cfg)
    for source, papers in results.items():
        print(f"{source}: {len(papers)}")
    return 0


def cmd_run(home: Path, *, dry_run: bool) -> int:
    cfg = config.load_config(home)
    run_date = datetime.now().strftime("%Y-%m-%d")
    started_at = datetime.now(UTC)

    store = Store(config.db_path())
    try:
        store.start_run(run_date, started_at)

        fetched = fetch_all_sources(cfg)
        counts = {source: len(papers) for source, papers in fetched.items()}
        all_papers = [p for papers in fetched.values() for p in papers]

        if cfg.sources.semanticscholar.enabled:
            all_papers = semanticscholar.enrich(
                all_papers,
                cfg.general.contact_email,
                base_delay_seconds=cfg.sources.semanticscholar.base_delay_seconds,
            )

        deduped = dedupe.dedupe_batch(all_papers)
        store.upsert_papers(deduped)

        candidates = store.get_candidates()

        pkl_path = config.profile_index_path()
        profile_md_path = home / cfg.profile.profile_md_path
        if build.needs_rebuild(pkl_path, profile_md_path):
            print("Rebuilding profile index (missing or stale) ...")
            prof_index = build.build_index(
                orcid_id=cfg.profile.orcid_id,
                profile_md_text=profile_md_path.read_text() if profile_md_path.exists() else "",
                contact_email=cfg.general.contact_email,
                recency_half_life_days=cfg.profile.recency_half_life_days,
                profile_md_dominance=cfg.profile.profile_md_dominance,
            )
            build.save_index(prof_index, pkl_path)
        else:
            prof_index = build.load_index(pkl_path)

        scored = score.score_candidates(candidates, prof_index, cfg.topics.keywords, cfg.scoring)
        capped = score.cap_candidates(scored, cfg.scoring.candidate_cap)
        shortlisted = score.top_shortlist(
            capped, cfg.scoring.shortlist_size, cfg.scoring.recent_slots
        )
        store.upsert_papers(shortlisted)

        print(f"Fetched: {counts}")
        print(f"Candidates: {len(candidates)} -> shortlisted: {len(shortlisted)}")
        for p in shortlisted:
            print(f"  {p.score:.3f}  {p.title}  [{p.id}]")

        if dry_run:
            store.finish_run(
                run_date,
                finished_at=datetime.now(UTC),
                status="ok",
                counts=counts,
                paper_of_day_id=None,
                degraded_reasons=["dry_run"],
                digest_path=None,
            )
            return 0

        from recto import pick, render, summarize
        from recto.deliver import email as deliver_email
        from recto.deliver import notify

        degraded_reasons: list[str] = []
        summarize_result = summarize.summarize_shortlist(
            shortlisted,
            profile_md_text=profile_md_path.read_text() if profile_md_path.exists() else "",
            cfg=cfg.llm,
            api_key=keychain.get_secret(keychain.SERVICE_OPENROUTER, "api-key"),
        )
        if summarize_result.degraded:
            degraded_reasons.append(summarize_result.degraded_reason or "llm_unreachable")

        for s in summarize_result.summaries:
            match = next((p for p in shortlisted if p.id == s.id), None)
            if match:
                match.summary = s.summary
        store.upsert_papers(shortlisted)

        paper_of_day, rationale = pick.resolve_pick(shortlisted, summarize_result)
        for p in shortlisted:
            store.mark_state(p.id, "shown")
        if paper_of_day:
            store.mark_picked(paper_of_day.id, run_date)

        markdown = render.render_markdown(
            run_date=run_date,
            shortlisted=shortlisted,
            paper_of_day=paper_of_day,
            rationale=rationale,
            degraded=bool(degraded_reasons),
            degraded_reasons=degraded_reasons,
        )
        digest_path = render.write_digest(run_date, markdown, config.digests_dir(home))

        if cfg.delivery.email:
            try:
                html_body = render.render_html_email(
                    run_date=run_date,
                    shortlisted=shortlisted,
                    paper_of_day=paper_of_day,
                    rationale=rationale,
                    degraded=bool(degraded_reasons),
                    degraded_reasons=degraded_reasons,
                    subject_prefix=cfg.delivery.email_cfg.subject_prefix,
                )
                subject_title = paper_of_day.title if paper_of_day else "Digest"
                deliver_email.send_email(
                    subject=f"{cfg.delivery.email_cfg.subject_prefix} {subject_title}",
                    html_body=html_body,
                    plain_body=markdown,
                    smtp_host=cfg.delivery.email_cfg.smtp_host,
                    smtp_port=cfg.delivery.email_cfg.smtp_port,
                    use_starttls=cfg.delivery.email_cfg.smtp_starttls,
                    from_addr=cfg.delivery.email_cfg.from_address,
                    to_addr=cfg.delivery.email_cfg.to_address,
                    username=cfg.delivery.email_cfg.smtp_username
                    or cfg.delivery.email_cfg.from_address,
                    password=keychain.get_secret(
                        keychain.SERVICE_OUTLOOK, cfg.delivery.email_cfg.from_address
                    ),
                )
            except Exception:
                logger.exception("email delivery failed")
                degraded_reasons.append("email_delivery_failed")

        if cfg.delivery.notification and paper_of_day:
            notify.send_notification(
                title="recto: today's paper",
                subtitle=paper_of_day.title,
                enabled=cfg.delivery.notification,
            )

        status = "degraded" if degraded_reasons else "ok"
        store.finish_run(
            run_date,
            finished_at=datetime.now(UTC),
            status=status,
            counts=counts,
            paper_of_day_id=paper_of_day.id if paper_of_day else None,
            degraded_reasons=degraded_reasons,
            digest_path=str(digest_path),
        )
        print(f"Digest written to {digest_path} (status: {status})")
        return 0
    finally:
        store.close()


def cmd_show(home: Path) -> int:
    store = Store(config.db_path())
    try:
        run = store.get_latest_run()
        if not run or not run.get("digest_path"):
            print("No digest found yet. Run `recto run` first.")
            return 1
        path = Path(run["digest_path"])
        if not path.is_absolute():
            path = home / path
        print(path.read_text())
        return 0
    finally:
        store.close()


def cmd_why(home: Path, paper_id: str) -> int:
    store = Store(config.db_path())
    try:
        paper = store.get_paper(paper_id)
        if not paper:
            print(f"No paper found with id {paper_id!r}", file=sys.stderr)
            return 1
        print(f"{paper.title}")
        print(f"score: {paper.score:.4f}")
        print("reasons:")
        for r in paper.score_reasons:
            print(f"  - {r}")
        return 0
    finally:
        store.close()


def cmd_install_agent(home: Path) -> int:
    from recto.launchd import install_agent

    plist_path = install_agent(home)
    print(f"Installed launchd agent at {plist_path}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="recto")
    parser.add_argument("--home", type=Path, default=None)
    sub = parser.add_subparsers(dest="command", required=True)

    p_bootstrap = sub.add_parser("bootstrap")
    p_bootstrap.add_argument("--orcid-id", default=DEFAULT_ORCID_ID)
    p_bootstrap.add_argument("--contact-email", default=DEFAULT_CONTACT_EMAIL)
    p_bootstrap.add_argument("--arxiv-category", action="append", dest="arxiv_categories")

    p_run = sub.add_parser("run")
    p_run.add_argument("--dry-run", action="store_true")

    sub.add_parser("fetch")
    sub.add_parser("show")

    p_why = sub.add_parser("why")
    p_why.add_argument("paper_id")

    sub.add_parser("install-agent")

    args = parser.parse_args(argv)
    home = args.home or config.home_dir()
    configure_logging(config.logs_dir() / "recto.log")

    if args.command == "bootstrap":
        return cmd_bootstrap(
            home,
            orcid_id=args.orcid_id,
            contact_email=args.contact_email,
            arxiv_categories=args.arxiv_categories or DEFAULT_ARXIV_CATEGORIES,
        )
    if args.command == "fetch":
        return cmd_fetch(home)
    if args.command == "run":
        return cmd_run(home, dry_run=args.dry_run)
    if args.command == "show":
        return cmd_show(home)
    if args.command == "why":
        return cmd_why(home, args.paper_id)
    if args.command == "install-agent":
        return cmd_install_agent(home)

    parser.error(f"unknown command {args.command!r}")
    return 2


if __name__ == "__main__":
    sys.exit(main())
